name: timtam
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive_ce: ^2.6.0
  hive_ce_flutter: ^2.1.0
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  fl_chart: ^0.66.2
  intl: ^0.19.0
  uuid: ^4.4.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_ce_generator: ^1.10.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_app.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon_app.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icon_app.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon_app.png"
